module.exports = [
	require("./computerRooms"),
	require("./user"),
	require("./maintenanceHistory"),
	require("./support"),
	require("./incidentReport"),
	require("./computer"),
	require("./computerTypes"),
	require("./software"),
	require("./device"),
	require("./computerSoftware"),
	require("./computerDevices"),
	require("./computerTypeSoftware"),
	require("./computerTypeDevices"),
	require("./reportDetails"),
];
